---
name: Security Scanning 🕵️

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Source checkout
        uses: actions/checkout@v4

      - name: 'Setup yq'
        uses: dcarbone/install-yq-action@v1.3.1

      - id: set-matrix
        run: echo "matrix=$(yq -o json build_versions.yaml | jq -c)" >> $GITHUB_OUTPUT

  scan_ci_container:
    name: 'Scan CI container'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build CI container
        uses: docker/build-push-action@v6
        with:
          tags: 'ci/voxbox:${{ matrix.rubygem_puppet }}'
          push: false
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            RUBYGEM_BUNDLER=${{ matrix.rubygem_bundler }}
            RUBYGEM_FACTER=${{ matrix.rubygem_facter }}
            RUBYGEM_MODULESYNC=${{ matrix.rubygem_modulesync }}
            RUBYGEM_ONCEOVER=${{ matrix.rubygem_onceover }}
            RUBYGEM_PUPPET_METADATA=${{ matrix.rubygem_puppet_metadata }}
            RUBYGEM_PUPPET=${{ matrix.rubygem_puppet }}
            RUBYGEM_RSPEC_JUNIT_FORMATTER=${{ matrix.rubygem_rspec_junit_formatter }}
            RUBYGEM_RUBOCOP_PERFORMANCE=${{ matrix.rubygem_rubocop-performance }}
            RUBYGEM_VOXPUPULI_ACCEPTANCE=${{ matrix.rubygem_voxpupuli-acceptance }}
            RUBYGEM_VOXPUPULI_RELEASE=${{ matrix.rubygem_voxpupuli-release }}
            RUBYGEM_VOXPUPULI_TEST=${{ matrix.rubygem_voxpupuli-test }}
            RUBYGEM_PUPPET_GHOSTBUSTER=${{ matrix.rubygem_puppet-ghostbuster }}

      - name: Scan image with Anchore Grype
        uses: anchore/scan-action@v6
        id: scan
        with:
          image: 'ci/voxbox:${{ matrix.rubygem_puppet }}'
          fail-build: false

      - name: Inspect action SARIF report
        run: jq . ${{ steps.scan.outputs.sarif }}

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
